name: tensorflow
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.6
    - numpy
    - matplotlib
    - jupyter
    - opencv3
    - scikit-learn
    - scipy
    - h5py
    - seaborn
    - pandas
    - tensorflow-gpu
    - pip:
        - git+https://github.com/fchollet/keras.git
